language: python

python:
  - '2.7'

env: SECRET_KEY='localtestsecretkey' DB_ENGINE='django.db.backends.postgresql_psycopg2'
  DB_USER='postgres' DB_HOST='localhost' DB_NAME='travis_ci_test' DB_PORT='5432'

install: pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: GPFEYMp5V9PtJOMvZYffGyQFhBtBaBi1sKWcY0UuwMSTqZQ/CmBZfDLlBjPWfuwMV3avnpsd1sq9odpEcp7F8pUPjbkoMf0HZ7zmVvFELgXcIINPiiY0I3ANhvWIpbuy38IbQeY8gl5tP/oYk+YL+rrM8d+ZMzIKU54Idr1C6qA=
  run:
    - python manage.py syncdb --noinput
    - python manage.py migrate
    - restart
